import { auth, signOut } from "@/auth";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.className} antialiased bg-black text-white flex flex-col h-[100vh]`}
      >
        <Navbar
          username={session?.user?.name ?? ""}
          loginServerComponent={
            <form
              className="inline"
              action={async () => {
                "use server";
                await signOut();
              }}
            >
              <button
                className="px-1 py-0.5 text-white text-[20px] underline underline-offset-1 cursor-pointer transition-colors hover:text-red-500 hover:bg-white decoration-2"
                type="submit"
              >
                Logout
              </button>
            </form>
          }
        />

        {children}
      </body>
    </html>
  );
}
